package example.tests;

    import static org.testng.Assert.assertEquals;
import static org.testng.Assert.fail;

import java.util.NoSuchElementException;
import java.util.concurrent.TimeUnit;

import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.support.ui.Select;
import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

    public class E2logTestcase {
      private WebDriver driver;
      private String baseUrl;
      private boolean acceptNextAlert = true;
      private StringBuffer verificationErrors = new StringBuffer();

      @BeforeClass(alwaysRun = true)
      public void setUp() throws Exception {
    	  System.setProperty("webdriver.chrome.driver", "/home/thrymr/Desktop/Mamatha/chromedriver");
        driver = new ChromeDriver();
        baseUrl = "http://ci.thrymr.net:2018/";
        driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
      }

      @Test
      public void testE2logTestcase() throws Exception {
    	  driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
        driver.get(baseUrl + "/");
        assertEquals(driver.getTitle(), "e2log");
        driver.findElement(By.cssSelector("button.btn.btn-readMore")).click();
        driver.findElement(By.cssSelector("button.transparent-gray-btn.btn")).click();
        driver.findElement(By.xpath("(//input[@type='text'])[2]")).clear();
        driver.findElement(By.xpath("(//input[@type='text'])[2]")).sendKeys("testselenium");
        driver.findElement(By.xpath("(//input[@type='text'])[3]")).clear();
        driver.findElement(By.xpath("(//input[@type='text'])[3]")).sendKeys("sele");
        driver.findElement(By.xpath("(//input[@type='text'])[4]")).clear();
        driver.findElement(By.xpath("(//input[@type='text'])[4]")).sendKeys("seleniumhq4@test.com");
        new Select(driver.findElement(By.id("country"))).selectByVisibleText("India");
        driver.findElement(By.xpath("(//input[@type='text'])[5]")).clear();
        driver.findElement(By.xpath("(//input[@type='text'])[5]")).sendKeys("thrymr");
        driver.findElement(By.xpath("(//input[@type='text'])[6]")).clear();
        driver.findElement(By.xpath("(//input[@type='text'])[6]")).sendKeys("8407923456");
        driver.findElement(By.xpath("(//input[@type='checkbox'])[2]")).click();
        driver.findElement(By.cssSelector("div.form-group.margin-top-20 > label.md-checkbox2 > span.checkmark")).click();
        driver.findElement(By.xpath("//button[@type='submit']")).click();
        driver.findElement(By.cssSelector("div.modal-footer > button.btn.rfqPrintBtn")).click();
        assertEquals(driver.getTitle(), "e2log");
        driver.findElement(By.xpath("//input[@type='email']")).clear();
        driver.findElement(By.xpath("//input[@type='email']")).sendKeys("e2log@thrymr.net");
        driver.findElement(By.xpath("//input[@type='Password']")).clear();
        driver.findElement(By.xpath("//input[@type='Password']")).sendKeys("e2Log@123");
        driver.findElement(By.cssSelector("button.rfqPrintBtn")).click();
        driver.findElement(By.linkText("User Management")).click();
        driver.findElement(By.xpath("//div[@id='customer-requests']/div/table/tbody/tr/td[7]/button")).click();
        driver.findElement(By.cssSelector("button.btn.btn-success")).click();
        driver.findElement(By.xpath("//div[@id='customer-requests']/div/table/tbody/tr/td[7]/button[2]")).click();
        driver.findElement(By.cssSelector("div.modal-body.modalBody > h4.modal-title")).click();
        driver.findElement(By.id("resend-link-modal")).click();
        driver.findElement(By.cssSelector("span.hidden-xs.text-uppercase")).click();
        driver.findElement(By.linkText("Sign out")).click();
        assertEquals(driver.getTitle(), "e2log");
        driver.findElement(By.xpath("(//input[@type='text'])[3]")).clear();
        driver.findElement(By.xpath("(//input[@type='text'])[3]")).sendKeys("selenium@test.com");
        new Select(driver.findElement(By.id("countryCode"))).selectByVisibleText("India (+91)");
        driver.findElement(By.xpath("(//input[@type='text'])[4]")).clear();
        driver.findElement(By.xpath("(//input[@type='text'])[4]")).sendKeys("7384748");
        driver.findElement(By.xpath("(//input[@type='text'])[5]")).clear();
        driver.findElement(By.xpath("(//input[@type='text'])[5]")).sendKeys("r##Rr");
        driver.findElement(By.xpath("(//input[@type='text'])[6]")).clear();
        driver.findElement(By.xpath("(//input[@type='text'])[6]")).sendKeys("www.seleno.com");
        driver.findElement(By.xpath("(//input[@type='text'])[7]")).clear();
        driver.findElement(By.xpath("(//input[@type='text'])[7]")).sendKeys("56786656");
        driver.findElement(By.xpath("(//input[@type='text'])[8]")).clear();
        driver.findElement(By.xpath("(//input[@type='text'])[8]")).sendKeys("56");
        driver.findElement(By.xpath("//textarea[@type='text']")).clear();
        driver.findElement(By.xpath("//textarea[@type='text']")).sendKeys("retrrr");
        driver.findElement(By.xpath("(//input[@type='text'])[9]")).clear();
        driver.findElement(By.xpath("(//input[@type='text'])[9]")).sendKeys("kapil towers");
        driver.findElement(By.xpath("(//input[@type='text'])[10]")).clear();
        driver.findElement(By.xpath("(//input[@type='text'])[10]")).sendKeys("46346346");
        new Select(driver.findElement(By.id("state"))).selectByVisibleText("Telangana");
        new Select(driver.findElement(By.id("city"))).selectByVisibleText("Hyderabad");
        driver.findElement(By.xpath("(//input[@type='text'])[11]")).clear();
        driver.findElement(By.xpath("(//input[@type='text'])[11]")).sendKeys("500032");
        driver.findElement(By.xpath("(//input[@type='text'])[15]")).clear();
        driver.findElement(By.xpath("(//input[@type='text'])[15]")).sendKeys("QA");
        driver.findElement(By.xpath("//input[@type='checkbox']")).click();
        driver.findElement(By.cssSelector("label.md-checkbox2")).click();
        driver.findElement(By.cssSelector("button.btn.rfqPrintBtn")).click();
        driver.findElement(By.cssSelector("button.btn.btn-success")).click();
        driver.findElement(By.xpath("//input[@type='email']")).click();
        driver.findElement(By.xpath("//input[@type='email']")).clear();
        driver.findElement(By.xpath("//input[@type='email']")).sendKeys("seleniumhq3@test.com");
        driver.findElement(By.xpath("//input[@type='Password']")).clear();
        driver.findElement(By.xpath("//input[@type='Password']")).sendKeys("e2LoG@123");
        driver.findElement(By.cssSelector("button.rfqPrintBtn.btn")).click();
        driver.findElement(By.xpath("//input[@type='Password']")).clear();
        driver.findElement(By.xpath("//input[@type='Password']")).sendKeys("e2Log@123");
        driver.findElement(By.cssSelector("button.rfqPrintBtn.btn")).click();
        driver.findElement(By.id("oldPassword")).clear();
        driver.findElement(By.id("oldPassword")).sendKeys("e2Log@123");
        driver.findElement(By.id("newPassword")).clear();
        driver.findElement(By.id("newPassword")).sendKeys("e2loG2123");
        driver.findElement(By.id("confirmPassword")).clear();
        driver.findElement(By.id("confirmPassword")).sendKeys("e2loG2123");
        driver.findElement(By.cssSelector("button.rfqPrintBtn.btn")).click();
        driver.findElement(By.xpath("//input[@type='email']")).clear();
        driver.findElement(By.xpath("//input[@type='email']")).sendKeys("selenium1@test.com");
        driver.findElement(By.xpath("//input[@type='Password']")).clear();
        driver.findElement(By.xpath("//input[@type='Password']")).sendKeys("e2loG2123");
        driver.findElement(By.cssSelector("button.rfqPrintBtn.btn")).click();
        driver.findElement(By.xpath("//input[@type='email']")).clear();
        driver.findElement(By.xpath("//input[@type='email']")).sendKeys("seleniumhq3@test.com");
        driver.findElement(By.cssSelector("button.rfqPrintBtn.btn")).click();
        driver.findElement(By.linkText("RFQ's")).click();
        driver.findElement(By.xpath("//input[@type='text']")).click();
        driver.findElement(By.xpath("//option[@value='3: CAD']")).click();
        new Select(driver.findElement(By.name("currency"))).selectByVisibleText("INR");
        driver.findElement(By.xpath("//input[@type='text']")).clear();
        driver.findElement(By.xpath("//input[@type='text']")).sendKeys("seleniumtest2");
        driver.findElement(By.cssSelector("button.btnpicker.btnpickerenabled")).click();
        driver.findElement(By.cssSelector("span.markcurrday")).click();
        driver.findElement(By.xpath("(//input[@type='text'])[2]")).clear();
        driver.findElement(By.xpath("(//input[@type='text'])[2]")).sendKeys("tester");
        driver.findElement(By.xpath("(//input[@type='text'])[3]")).clear();
        driver.findElement(By.xpath("(//input[@type='text'])[3]")).sendKeys("selenium@test.com");
        driver.findElement(By.xpath("//textarea[@type='text']")).clear();
        driver.findElement(By.xpath("//textarea[@type='text']")).sendKeys("selenium1@test.com,selenium2@test.com");
        new Select(driver.findElement(By.id("contactPersonMobileCountry"))).selectByVisibleText("American Samoa (+1684)");
        driver.findElement(By.xpath("(//input[@type='text'])[4]")).click();
        driver.findElement(By.xpath("(//input[@type='text'])[4]")).clear();
        driver.findElement(By.xpath("(//input[@type='text'])[4]")).sendKeys("346346346");
        driver.findElement(By.xpath("(//input[@type='text'])[5]")).clear();
        driver.findElement(By.xpath("(//input[@type='text'])[5]")).sendKeys("436346346");
        new Select(driver.findElement(By.id("officeLandNumberCountry"))).selectByVisibleText("Aland Islands (+)");
        driver.findElement(By.cssSelector("div.c-btn")).click();
        driver.findElement(By.xpath("//div[@id='home']/div/form/div[3]/div/div[4]/div[2]/div/angular2-multiselect/div/div[2]/div[3]/div/label")).click();
        driver.findElement(By.cssSelector("div.col-md-12 > div.col-md-12 > div > div.row")).click();
        driver.findElement(By.name("paymentOption")).click();
        driver.findElement(By.cssSelector("span.label-text")).click();
        driver.findElement(By.xpath("//button[@type='submit']")).click();
        new Select(driver.findElement(By.id("state"))).selectByVisibleText("Quay Side");
        driver.findElement(By.cssSelector("button.btnpicker.btnpickerenabled")).click();
        driver.findElement(By.xpath("//tr[4]/td[2]/div")).click();
        new Select(driver.findElement(By.name("deliveryLocation"))).selectByVisibleText("Warehouse");
        driver.findElement(By.xpath("(//button[@type='button'])[3]")).click();
        driver.findElement(By.xpath("//tr[4]/td[5]/div/span")).click();
        new Select(driver.findElement(By.id("pickupCountryId"))).selectByVisibleText("Algeria");
        driver.findElement(By.xpath("//option[@value='4']")).click();
        new Select(driver.findElement(By.id("pickupStateId"))).selectByVisibleText("Ain Temouchent");
        driver.findElement(By.xpath("//option[@value='840']")).click();
        new Select(driver.findElement(By.id("deliveryCountryId"))).selectByVisibleText("Albania");
        driver.findElement(By.xpath("(//option[@value='3'])[4]")).click();
        new Select(driver.findElement(By.id("deliveryStateId"))).selectByVisibleText("Fier");
        driver.findElement(By.xpath("(//option[@value='75'])[5]")).click();
        new Select(driver.findElement(By.id("pickupCityId"))).selectByVisibleText("El Amria");
        driver.findElement(By.xpath("//input[@type='text']")).clear();
        driver.findElement(By.xpath("//input[@type='text']")).sendKeys("6346346");
        new Select(driver.findElement(By.id("deliveryCityId"))).selectByVisibleText("Bashkia Divjake");
        driver.findElement(By.xpath("(//input[@type='text'])[5]")).click();
        driver.findElement(By.xpath("(//input[@type='text'])[5]")).clear();
        driver.findElement(By.xpath("(//input[@type='text'])[5]")).sendKeys("346346346");
        driver.findElement(By.xpath("//textarea[@type='text']")).clear();
        driver.findElement(By.xpath("//textarea[@type='text']")).sendKeys("ADcsfasfa");
        driver.findElement(By.xpath("(//textarea[@type='text'])[2]")).clear();
        driver.findElement(By.xpath("(//textarea[@type='text'])[2]")).sendKeys("sfasfasfasf");
        driver.findElement(By.xpath("(//input[@type='text'])[2]")).click();
        driver.findElement(By.xpath("(//input[@type='text'])[2]")).clear();
        driver.findElement(By.xpath("(//input[@type='text'])[2]")).sendKeys("asfas");
        driver.findElement(By.xpath("(//input[@type='text'])[3]")).click();
        driver.findElement(By.xpath("(//input[@type='text'])[3]")).clear();
        driver.findElement(By.xpath("(//input[@type='text'])[3]")).sendKeys("safas@dfg.jhg");
        new Select(driver.findElement(By.id("pickupLandLineNumberCountry"))).selectByVisibleText("Ghana (+233)");
        driver.findElement(By.xpath("(//input[@type='text'])[4]")).clear();
        driver.findElement(By.xpath("(//input[@type='text'])[4]")).sendKeys("54734");
        driver.findElement(By.xpath("//input[@type='number']")).clear();
        driver.findElement(By.xpath("//input[@type='number']")).sendKeys("75474");
        driver.findElement(By.xpath("(//input[@type='text'])[6]")).clear();
        driver.findElement(By.xpath("(//input[@type='text'])[6]")).sendKeys("dfhhdf");
        driver.findElement(By.xpath("(//input[@type='text'])[7]")).clear();
        driver.findElement(By.xpath("(//input[@type='text'])[7]")).sendKeys("dfhdfh@dfh.jfj");
        driver.findElement(By.xpath("(//input[@type='text'])[8]")).clear();
        driver.findElement(By.xpath("(//input[@type='text'])[8]")).sendKeys("6346346");
        driver.findElement(By.name("deliveryMobileNumber")).click();
        driver.findElement(By.name("deliveryMobileNumber")).clear();
        driver.findElement(By.name("deliveryMobileNumber")).sendKeys("34634634");
        driver.findElement(By.cssSelector("input[type=\"checkbox\"]")).click();
        driver.findElement(By.cssSelector("span.checkmark")).click();
        driver.findElement(By.id("Off Loading at destination location")).click();
        driver.findElement(By.xpath("//div[10]/div/div[3]/label/span")).click();
        driver.findElement(By.id("Terminal/ Port Handling (Discharge Port)")).click();
        driver.findElement(By.id("Terminal/ Port Handling (Load Port)")).click();
        driver.findElement(By.id("Customs Clearance (Discharge Port)")).click();
        driver.findElement(By.cssSelector("my-date-picker[name=\"internationalTransitCommencementDate\"] > div.mydp > div.selectiongroup.ng-star-inserted > div.selbtngroup > button.btnpicker.btnpickerenabled")).click();
        driver.findElement(By.xpath("//tr[4]/td[2]/div/span")).click();
        driver.findElement(By.id("isPartialQuoteAllowed")).click();
        driver.findElement(By.cssSelector("span.label-text")).click();
        driver.findElement(By.xpath("//button[@type='submit']")).click();
        driver.findElement(By.xpath("//input[@type='text']")).click();
        driver.findElement(By.xpath("//input[@type='text']")).clear();
        driver.findElement(By.xpath("//input[@type='text']")).sendKeys("item1");
        driver.findElement(By.xpath("(//input[@type='text'])[2]")).clear();
        driver.findElement(By.xpath("(//input[@type='text'])[2]")).sendKeys("r22R@@");
        driver.findElement(By.xpath("(//input[@type='text'])[3]")).clear();
        driver.findElement(By.xpath("(//input[@type='text'])[3]")).sendKeys("12");
        driver.findElement(By.xpath("//input[@type='tel']")).clear();
        driver.findElement(By.xpath("//input[@type='tel']")).sendKeys("21241");
        driver.findElement(By.xpath("//input[@type='number']")).clear();
        driver.findElement(By.xpath("//input[@type='number']")).sendKeys("1244");
        new Select(driver.findElement(By.xpath("//select"))).selectByVisibleText("MT");
        driver.findElement(By.xpath("(//input[@type='number'])[2]")).clear();
        driver.findElement(By.xpath("(//input[@type='number'])[2]")).sendKeys("24");
        driver.findElement(By.xpath("(//input[@type='number'])[3]")).clear();
        driver.findElement(By.xpath("(//input[@type='number'])[3]")).sendKeys("24");
        driver.findElement(By.xpath("(//input[@type='number'])[4]")).clear();
        driver.findElement(By.xpath("(//input[@type='number'])[4]")).sendKeys("24");
        new Select(driver.findElement(By.xpath("//div[2]/div[2]/select"))).selectByVisibleText("IN");
        new Select(driver.findElement(By.xpath("//div[3]/select"))).selectByVisibleText("Class 1");
        new Select(driver.findElement(By.xpath("//div[4]/select"))).selectByVisibleText("New");
        driver.findElement(By.id("n40")).click();
        driver.findElement(By.xpath("//div[2]/div/div/label[2]")).click();
        driver.findElement(By.xpath("(//input[@name='originPort'])[2]")).click();
        driver.findElement(By.xpath("//label[2]/span")).click();
        driver.findElement(By.name("destinationPort")).click();
        driver.findElement(By.xpath("//div[2]/div/div/label/span")).click();
        driver.findElement(By.cssSelector("button.rfqPrintBtn.as_marLF_15")).click();
        driver.findElement(By.id("info")).click();
        driver.findElement(By.cssSelector("span.checkmark")).click();
        driver.findElement(By.id("1")).click();
        driver.findElement(By.xpath("//div[@id='#addition_requirement']/div[2]/div[2]/div/div/div[8]/label/span")).click();
        driver.findElement(By.id("6")).click();
        driver.findElement(By.xpath("//div[@id='#addition_requirement']/div[2]/div[2]/div/div/div[4]/label/span")).click();
        driver.findElement(By.id("3")).click();
        driver.findElement(By.xpath("//div[@id='#addition_requirement']/div[2]/div[2]/div/div/div[10]/label/span")).click();
        driver.findElement(By.id("8")).click();
        driver.findElement(By.id("11")).click();
        driver.findElement(By.id("12")).click();
        driver.findElement(By.id("14")).click();
        driver.findElement(By.xpath("//button[@type='submit']")).click();
        driver.findElement(By.cssSelector("span.checkmark")).click();
        driver.findElement(By.xpath("(//input[@type='checkbox'])[11]")).click();
        driver.findElement(By.xpath("//form[@id='form']/div[2]/div/button[3]")).click();
        driver.findElement(By.linkText("testselenium sele")).click();
        driver.findElement(By.linkText("Sign out")).click();
        assertEquals(driver.getTitle(), "e2log");
        driver.findElement(By.xpath("//input[@type='email']")).clear();
        driver.findElement(By.xpath("//input[@type='email']")).sendKeys("e2log@thrymr.net");
        driver.findElement(By.xpath("//input[@type='Password']")).clear();
        driver.findElement(By.xpath("//input[@type='Password']")).sendKeys("e2Log@123");
        driver.findElement(By.cssSelector("button.rfqPrintBtn")).click();
        driver.findElement(By.cssSelector("span > a")).click();
        driver.findElement(By.cssSelector("button.btn.rfqPrintBtn")).click();
        driver.findElement(By.cssSelector("button.apporveButton")).click();
        driver.findElement(By.cssSelector("button.btn.btn-success")).click();
        driver.findElement(By.xpath("//div[@id='toast-container']/div/div")).click();
        driver.findElement(By.cssSelector("span.hidden-xs.text-uppercase")).click();
        driver.findElement(By.linkText("Sign out")).click();
        assertEquals(driver.getTitle(), "e2log");
        driver.findElement(By.xpath("//input[@type='email']")).clear();
        driver.findElement(By.xpath("//input[@type='email']")).sendKeys("suryajyoti.bisen@thrymr.net");
        driver.findElement(By.xpath("//input[@type='Password']")).clear();
        driver.findElement(By.xpath("//input[@type='Password']")).sendKeys("e2loG@123");
        driver.findElement(By.cssSelector("button.rfqPrintBtn.btn")).click();
        driver.findElement(By.xpath("//li[2]/a/span")).click();
        driver.findElement(By.cssSelector("button.rfqPrintBtn")).click();
        driver.findElement(By.xpath("//div[@id='content1']/app-lsp-manage-quotation-rfqreceived/div[2]/app-lsp-view-rfq/div/div/div/div[2]/button")).click();
        driver.findElement(By.id("11")).click();
        driver.findElement(By.cssSelector("span.checkmark")).click();
        driver.findElement(By.id("14")).click();
        driver.findElement(By.xpath("//div[@id='print-drafted-rfq1']/div/div[2]/div/div/ul/li[4]/div/label/span")).click();
        driver.findElement(By.id("13")).click();
        driver.findElement(By.xpath("//div[@id='print-drafted-rfq1']/div/div[2]/div/div/ul/li[3]/div/label/span")).click();
        driver.findElement(By.name("namead")).clear();
        driver.findElement(By.name("namead")).sendKeys("12");
        driver.findElement(By.xpath("(//input[@name='namead'])[2]")).clear();
        driver.findElement(By.xpath("(//input[@name='namead'])[2]")).sendKeys("23");
        driver.findElement(By.xpath("(//input[@name='namead'])[3]")).clear();
        driver.findElement(By.xpath("(//input[@name='namead'])[3]")).sendKeys("12");
        driver.findElement(By.xpath("//div[@id='accordian']/div[2]/div[2]/a/div/div/div[3]/span/i")).click();
        driver.findElement(By.name("ltforkLiftPrice")).clear();
        driver.findElement(By.name("ltforkLiftPrice")).sendKeys("12");
        driver.findElement(By.name("ltcranesPrice")).click();
        driver.findElement(By.name("ltcranesPrice")).clear();
        driver.findElement(By.name("ltcranesPrice")).sendKeys("12");
        driver.findElement(By.name("ltenclosedTruckPrice")).click();
        driver.findElement(By.name("ltenclosedTruckPrice")).clear();
        driver.findElement(By.name("ltenclosedTruckPrice")).sendKeys("12");
        driver.findElement(By.name("ltflatBedPrice")).click();
        driver.findElement(By.name("ltflatBedPrice")).clear();
        driver.findElement(By.name("ltflatBedPrice")).sendKeys("12");
        driver.findElement(By.name("ltlowBedPrice")).clear();
        driver.findElement(By.name("ltlowBedPrice")).sendKeys("12");
        driver.findElement(By.name("lthydraulicPrice")).click();
        driver.findElement(By.name("lthydraulicPrice")).clear();
        driver.findElement(By.name("lthydraulicPrice")).sendKeys("12");
        driver.findElement(By.name("ltescortCharges")).clear();
        driver.findElement(By.name("ltescortCharges")).sendKeys("12");
        driver.findElement(By.name("ltroadPermits")).click();
        driver.findElement(By.name("ltroadPermits")).clear();
        driver.findElement(By.name("ltroadPermits")).sendKeys("12");
        driver.findElement(By.name("ltotherCostDescription")).clear();
        driver.findElement(By.name("ltotherCostDescription")).sendKeys("dff");
        driver.findElement(By.name("ltotherCost")).clear();
        driver.findElement(By.name("ltotherCost")).sendKeys("13");
        driver.findElement(By.name("camanpowerPrice")).clear();
        driver.findElement(By.name("camanpowerPrice")).sendKeys("13");
        driver.findElement(By.name("catravelAccomodationRate")).clear();
        driver.findElement(By.name("catravelAccomodationRate")).sendKeys("13");
        driver.findElement(By.xpath("//div[@id='accordian']/div[3]/div[2]/a/div/div/div[3]/span/i")).click();
        driver.findElement(By.name("cclagencyFeesPercentage")).click();
        driver.findElement(By.name("cclagencyFeesPercentage")).clear();
        driver.findElement(By.name("cclagencyFeesPercentage")).sendKeys("13");
        driver.findElement(By.name("cclstatutoryCharges")).click();
        driver.findElement(By.name("cclstatutoryCharges")).clear();
        driver.findElement(By.name("cclstatutoryCharges")).sendKeys("13");
        driver.findElement(By.id("data-1")).clear();
        driver.findElement(By.id("data-1")).sendKeys("/home/thrymr/Desktop/500_error.png");
        driver.findElement(By.id("data-6")).clear();
        driver.findElement(By.id("data-6")).sendKeys("/home/thrymr/Desktop/500_error.png");
        driver.findElement(By.id("data-3")).clear();
        driver.findElement(By.id("data-3")).sendKeys("/home/thrymr/Desktop/500_error.png");
        driver.findElement(By.id("data-8")).clear();
        driver.findElement(By.id("data-8")).sendKeys("/home/thrymr/Desktop/alignment issue.png");
        driver.findElement(By.id("data-11")).clear();
        driver.findElement(By.id("data-11")).sendKeys("/home/thrymr/Desktop/500_error.png");
        driver.findElement(By.id("data-12")).clear();
        driver.findElement(By.id("data-12")).sendKeys("/home/thrymr/Desktop/external developers .png");
        driver.findElement(By.id("manageQuoteTerms")).click();
        driver.findElement(By.cssSelector("div.padding-10 > label.md-checkbox2.lineheight-20 > span.checkmark")).click();
        driver.findElement(By.cssSelector("div.col-md-6 > button[name=\"button\"]")).click();
        driver.findElement(By.cssSelector("button.btn.btn-success")).click();
        driver.findElement(By.cssSelector("span.hidden-xs.text-uppercase")).click();
        driver.findElement(By.linkText("Sign out")).click();
        assertEquals(driver.getTitle(), "e2log");
        driver.findElement(By.xpath("//input[@type='email']")).clear();
        driver.findElement(By.xpath("//input[@type='email']")).sendKeys("e2log@thrymr.net");
        driver.findElement(By.xpath("//input[@type='Password']")).clear();
        driver.findElement(By.xpath("//input[@type='Password']")).sendKeys("e2Log@123");
        driver.findElement(By.cssSelector("button.rfqPrintBtn")).click();
        driver.findElement(By.cssSelector("li.collapsed.ng-star-inserted > a > span > a")).click();
        driver.findElement(By.cssSelector("button.btn.rfqPrintBtn")).click();
        driver.findElement(By.cssSelector("button.apporveButton.ng-star-inserted")).click();
        driver.findElement(By.cssSelector("button.btn.btn-success")).click();
        driver.findElement(By.linkText("admin e2log")).click();
        driver.findElement(By.linkText("Sign out")).click();
        assertEquals(driver.getTitle(), "e2log");
        assertEquals(driver.getTitle(), "e2log");
        driver.findElement(By.xpath("//input[@type='email']")).clear();
        driver.findElement(By.xpath("//input[@type='email']")).sendKeys("seleniumhq3@test.com");
        driver.findElement(By.xpath("//input[@type='Password']")).clear();
        driver.findElement(By.xpath("//input[@type='Password']")).sendKeys("e2loG@123");
        driver.findElement(By.cssSelector("button.rfqPrintBtn.btn")).click();
        driver.findElement(By.cssSelector("button.rfqPrintBtn.btn")).click();
        driver.findElement(By.cssSelector("button.rfqPrintBtn.btn")).click();
        driver.findElement(By.cssSelector("button.rfqPrintBtn.btn")).click();
        driver.findElement(By.xpath("//input[@type='Password']")).clear();
        driver.findElement(By.xpath("//input[@type='Password']")).sendKeys("e2lOg@123");
        driver.findElement(By.cssSelector("button.rfqPrintBtn.btn")).click();
        driver.findElement(By.xpath("//input[@type='Password']")).clear();
        driver.findElement(By.xpath("//input[@type='Password']")).sendKeys("e2Log@123");
        driver.findElement(By.cssSelector("button.rfqPrintBtn.btn")).click();
        driver.findElement(By.xpath("//input[@type='Password']")).clear();
        driver.findElement(By.xpath("//input[@type='Password']")).sendKeys("E2LOg@123");
        driver.findElement(By.cssSelector("button.rfqPrintBtn.btn")).click();
        driver.findElement(By.xpath("//input[@type='Password']")).clear();
        driver.findElement(By.xpath("//input[@type='Password']")).sendKeys("e2loG@123");
        driver.findElement(By.cssSelector("button.rfqPrintBtn.btn")).click();
        driver.findElement(By.linkText("RFQ's")).click();
        driver.findElement(By.linkText("Create New RFQ")).click();
        driver.findElement(By.xpath("//a[contains(@href, '/customer/quotations/allquotations')]")).click();
        driver.findElement(By.xpath("//button")).click();
        driver.findElement(By.xpath("//button[@value='16']")).click();
        driver.findElement(By.linkText("Quotes Shortlist")).click();
        driver.findElement(By.name("singlebutton")).click();
        driver.findElement(By.cssSelector("button.btnpicker.btnpickerenabled")).click();
        driver.findElement(By.cssSelector("span.markcurrday")).click();
        driver.findElement(By.cssSelector("my-date-picker[name=\"eDate\"] > div.mydp > div.selectiongroup.ng-star-inserted > div.selbtngroup > button.btnpicker.btnpickerenabled")).click();
        driver.findElement(By.cssSelector("my-date-picker[name=\"eDate\"] > div.mydp > div.selectiongroup.ng-star-inserted > div.selbtngroup > button.btnpicker.btnpickerenabled")).click();
        driver.findElement(By.cssSelector("my-date-picker[name=\"eDate\"] > div.mydp > div.selectiongroup.ng-star-inserted > div.selbtngroup > button.btnpicker.btnpickerenabled")).click();
        driver.findElement(By.cssSelector("span.markcurrday")).click();
        driver.findElement(By.xpath("(//button[@type='button'])[3]")).click();
        driver.findElement(By.cssSelector("button.btnpicker.btnpickerenabled")).click();
        driver.findElement(By.xpath("//div[@id='myModal']/div/div/div[2]/form/div/div/div/my-date-picker/div/div[2]/table[2]/tbody/tr[4]/td[2]/div/span")).click();
        driver.findElement(By.cssSelector("my-date-picker[name=\"eDate\"] > div.mydp > div.selectiongroup.ng-star-inserted > div.selbtngroup > button.btnpicker.btnpickerenabled")).click();
        driver.findElement(By.xpath("//div[@id='myModal']/div/div/div[2]/form/div/div[3]/div/my-date-picker/div/div[2]/table[2]/tbody/tr[4]/td[2]/div/span")).click();
        driver.findElement(By.xpath("(//button[@type='button'])[8]")).click();
        driver.findElement(By.xpath("(//button[@type='button'])[5]")).click();
        driver.findElement(By.name("sub")).click();
        driver.findElement(By.linkText("Optimize Quotes")).click();
        driver.findElement(By.linkText("LSP Wise")).click();
        driver.findElement(By.linkText("Lowest Cost/ Duration/ Customised")).click();
        driver.findElement(By.id("myTab")).click();
        driver.findElement(By.linkText("LSP Wise")).click();
        driver.findElement(By.linkText("Recommended")).click();
        driver.findElement(By.linkText("Lowest Cost/ Duration/ Customised")).click();
        driver.findElement(By.linkText("LSP Wise")).click();
        driver.findElement(By.linkText("Recommended")).click();
        driver.findElement(By.linkText("Reverse Auction")).click();
        driver.findElement(By.linkText("Optimize Quotes")).click();
        driver.findElement(By.linkText("Lowest Cost/ Duration/ Customised")).click();
        driver.findElement(By.linkText("Lowest Cost/ Duration/ Customised")).click();
        driver.findElement(By.linkText("LSP Wise")).click();
        driver.findElement(By.linkText("Reverse Auction")).click();
        driver.findElement(By.linkText("Optimize Quotes")).click();
        driver.findElement(By.linkText("Reverse Auction")).click();
        driver.findElement(By.linkText("Optimize Quotes")).click();
        driver.findElement(By.linkText("Lowest Cost/ Duration/ Customised")).click();
        driver.findElement(By.linkText("LSP Wise")).click();
        driver.findElement(By.linkText("Recommended")).click();
        driver.findElement(By.linkText("Reverse Auction")).click();
        driver.findElement(By.linkText("Optimize Quotes")).click();
        driver.findElement(By.linkText("Lowest Cost/ Duration/ Customised")).click();
        driver.findElement(By.linkText("LSP Wise")).click();
        driver.findElement(By.linkText("Recommended")).click();
        driver.findElement(By.linkText("Reverse Auction")).click();
        driver.findElement(By.linkText("Optimize Quotes")).click();
        driver.findElement(By.linkText("Lowest Cost/ Duration/ Customised")).click();
        driver.findElement(By.linkText("LSP Wise")).click();
        driver.findElement(By.linkText("Reverse Auction")).click();
        driver.findElement(By.linkText("Optimize Quotes")).click();
        driver.findElement(By.linkText("Lowest Cost/ Duration/ Customised")).click();
        driver.findElement(By.linkText("LSP Wise")).click();
        driver.findElement(By.linkText("Recommended")).click();
        driver.findElement(By.linkText("Reverse Auction")).click();
        driver.findElement(By.linkText("Optimize Quotes")).click();
        driver.findElement(By.linkText("Reverse Auction")).click();
      }

      @AfterClass(alwaysRun = true)
      public void tearDown() throws Exception {
        driver.quit();
        String verificationErrorString = verificationErrors.toString();
        if (!"".equals(verificationErrorString)) {
          fail(verificationErrorString);
        }
      }

      private boolean isElementPresent(By by) {
        try {
          driver.findElement(by);
          return true;
        } catch (NoSuchElementException e) {
          return false;
        }
      }

      private boolean isAlertPresent() {
        try {
          driver.switchTo().alert();
          return true;
        } catch (NoAlertPresentException e) {
          return false;
        }
      }

      private String closeAlertAndGetItsText() {
        try {
          Alert alert = driver.switchTo().alert();
          String alertText = alert.getText();
          if (acceptNextAlert) {
            alert.accept();
          } else {
            alert.dismiss();
          }
          return alertText;
        } finally {
          acceptNextAlert = true;
        }
      }}